apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-client-1
  namespace: default
  labels:
     app: collector-client-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector-client-1
  template:
    metadata:
      labels:
        app: collector-client-1
    spec:
      containers:
      - name: collector-client-1
        image: us.icr.io/iron-funnel-test/if-collector-pixel:v1
        ports:
          - containerPort: 7701